### PR TITLE
feat: Add support for workerd

### PR DESCRIPTION
**Pull request by arv**
This allows Cloudflare Workers to import xxhash-wasm as a module.

In the workers runtime you cannot instantiate a WebAssembly module from an ArrayBuffer. This is to prevent code from code injection attacks. Instead the runtime can only import a WebAssembly module from a relative path (it is handled by their bundler).

See https://developers.cloudflare.com/workers/runtime-apis/webassembly/javascript/ for more details on how to import a WebAssembly module in the workers runtime.

To allow workerd to import xxhash-wasm as a module, we add a conditional export in the package.json file. This allows the workerd runtime to import the module from the src/index.workerd.js file.

See https://developers.cloudflare.com/workers/wrangler/bundling/#conditional-exports for more details on how to use conditional exports in a workers project.

The rollup config has been updated to generate one more target, workerd/xxhash-wasm.js. Rollup also copies the wasm file to the workerd directory.

The code (src/index.js) has been changed to allow sharing code between these different targets.

### CODE REVIEW

**Comment by arv** [comment]
If anyone else wants to use this I published our fork to npm as [@rocicorp/xxhash-wasm](https://www.npmjs.com/package/@rocicorp/xxhash-wasm)

**Comment by arv** [comment]
@jungomi Any chance to get a comment on this?

**Comment by marcusdarmstrong** [comment]
It's potentially worth declaring the [expected capnp](https://github.com/cloudflare/workerd/blob/main/src/workerd/server/workerd.capnp#L253) that's associated with this structure, though I've never used Wrangler so I'm unfamiliar with its expectations here. We use workerd directly but I haven't needed to get xxhash working inside of that environment yet—seems like a wise thing to have done, though.

Code changes lgtm though.

**Comment by marcusdarmstrong** [comment]
>The capnp file you are linking to is used to describe the module kind that workerd supports. This is a low level protocol and if you use wrangler (cli) or Cloudflare's REST API you do not need to generated capnp files (AFAIK). I do not see what (or how) you expect to use a capnp file in the context of this PR.

Yeah fair enough. As noted, we don't use Wrangler and write (actually mostly generate) our capnp ourselves so I wasn't sure what the ecosystem expectations were here, but it would be hypothetically possible to publish a capnp module that defines the relevant Module declaration(s), such that they could be imported directly in the application capnp, but perhaps Wrangler handles this for you.

**Comment by arv** [comment]
> but it would be hypothetically possible to publish a capnp module that defines the relevant Module declaration(s)

Interesting. I will see if I can figure out how this works and how to test that. I only tested this using the wrangler cli.

**Comment by jungomi** [comment]
For me it looks good as well, as from the looks of it, nothing else is really changed, just that it provides an additional version for `workerd`.

Can you add a note to the Readme that it works for `workerd` and anything else that might be necessary to know? I haven't really used Cloudflare workers so I don't know what additional information would be helpful to get started using it in a worker.
But if there is nothing else to add, it is at least worth pointing it out in the Readme that they are supported.

**Comment by arv** [comment]
I updated the README. Please take a look.

**Comment by jungomi** [comment]
All good, thanks for the PR.

**Pull request merged**
